{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "order-lifecycle.fullname" . }}
  labels:
    {{- include "order-lifecycle.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "order-lifecycle.backendName" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: {{ include "order-lifecycle.backendName" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: {{ include "order-lifecycle.backendName" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: {{ include "order-lifecycle.backendName" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "order-lifecycle.frontendName" . }}
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}

