package com.example.leadflow.workflow

import com.example.leadflow.opportunity.OpportunityBriefInput
import com.example.leadflow.opportunity.OpportunityCreateRequest
import com.example.leadflow.opportunity.OpportunityLineInput
import com.example.leadflow.opportunity.OpportunityService
import java.math.BigDecimal
import java.net.CookieManager
import java.net.CookiePolicy
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.time.Duration
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Assumptions.assumeTrue
import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.TestConstructor

@SpringBootTest
@TestConstructor(autowireMode = TestConstructor.AutowireMode.ALL)
class WorkflowCompatibilityTest(
    private val opportunityService: OpportunityService,
    private val workflowReadRepository: WorkflowReadRepository,
) {

    private val httpClient = HttpClient.newBuilder()
        .cookieHandler(CookieManager(null, CookiePolicy.ACCEPT_ALL))
        .followRedirects(HttpClient.Redirect.ALWAYS)
        .connectTimeout(Duration.ofSeconds(10))
        .build()

    @Test
    fun `opportunity workflow produces records visible to ofbiz pages`() {
        assumeTrue(canReach("https://localhost:8443/partymgr/"))

        val suffix = System.currentTimeMillis().toString().takeLast(6)
        val opportunity = opportunityService.createOpportunity(
            OpportunityCreateRequest(
                firstName = "Codex$suffix",
                lastName = "Lead",
                email = "codex+$suffix@example.com",
                companyName = "Codex Labs $suffix",
            )
        )

        opportunityService.saveBrief(
            opportunity.partyId,
            OpportunityBriefInput(
                title = "Warehouse headset refresh $suffix",
                notes = "Generated by automated compatibility test",
                lines = listOf(
                    OpportunityLineInput(
                        description = "Two round gizmos",
                        productId = "GZ-2644",
                        quantity = BigDecimal("2"),
                        unitPrice = BigDecimal("24.50"),
                    )
                ),
            )
        )

        val quoteReady = opportunityService.createQuote(opportunity.partyId)
        val quoteId = quoteReady.latestQuoteId ?: error("Expected quote id after quote creation")
        val requestId = workflowReadRepository.findLatestRequestIdForLead(opportunity.partyId)
            ?: error("Expected request id after saving the brief")

        login("partymgr")
        assertPageContains("/partymgr/control/findparty?partyId=${opportunity.partyId}", opportunity.partyId)
        assertPageContains("/ordermgr/control/FindRequest?custRequestId=$requestId", requestId)
        assertPageContains("/ordermgr/control/findquotes?quoteId=$quoteId", quoteId)
    }

    private fun canReach(url: String): Boolean = try {
        val response = httpClient.send(
            HttpRequest.newBuilder(URI.create(url)).GET().build(),
            HttpResponse.BodyHandlers.discarding(),
        )
        response.statusCode() in 200..399
    } catch (_: Exception) {
        false
    }

    private fun login(app: String) {
        val body = "USERNAME=admin&PASSWORD=ofbiz"
        val request = HttpRequest.newBuilder(URI.create("https://localhost:8443/$app/control/login"))
            .header("Content-Type", "application/x-www-form-urlencoded")
            .POST(HttpRequest.BodyPublishers.ofString(body))
            .build()

        httpClient.send(request, HttpResponse.BodyHandlers.ofString())
    }

    private fun assertPageContains(path: String, expected: String) {
        val request = HttpRequest.newBuilder(URI.create("https://localhost:8443$path"))
            .GET()
            .build()
        val response = httpClient.send(request, HttpResponse.BodyHandlers.ofString())
        assertTrue(
            response.body().contains(expected),
            "Expected OFBiz page $path to contain $expected but it did not.",
        )
    }
}
